spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\Users\user\Documents\GitHub\MY-PLANT-DIARY-Server\src\main\resources\static
#      location: /Users/haeyoon/Desktop/Dev/test/MY-PLANT-DIARY-Server/src/main/resources/static
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:h2:tcp://localhost/~/myplantdiary
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
#          ddl-auto: create
    ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
#    root: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace